### ISSUE TITLE
Saying its the "fastest" inheritance library is disingenuous

### ISSUE THREAD

**Issue by fresheneesz** [javascript/augment#11]
Its certainly faster than some, but calling it the fastest either means you're not trying to be truthful, or you just didn't do your research. Here's a perf test someone that knows how to write them did that includes augment: http://jsperf.com/js-inheritance-method-calls/7

**Comment by aaditmshah** [comment]
At the time that I wrote this library it was indeed the smallest and the fastest. Now, I don't really care whether I'm being 100% truthful. The fact of the matter is that my library is pretty fast, and considering the size of my library (30 source lines of code, 10 if you don't consider the boilerplate) I would say that it is worth every byte.

Now compare that to the size of the [ClassManager](https://github.com/kogarashisan/ClassManager/blob/master/lib/class_manager.js) library created by the &ldquo;someone&rdquo; who wrote the tests that you referenced. It's 962 source lines of code. That's 32 times as big as augment and in terms of speed it is only twice as fast. Hence, per byte my library is 16 times faster.

Finally, when it comes to writing real world code I don't think object creation or method call performance would ever be a bottleneck. The real bottleneck would be related to the problem that you're trying to solve and the algorithm that you use. Trying to optimize classes is usually just a waste of time because the payoffs are very small.

To quote Donald Knuth, one of the most famous programmers:

> Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%.

Optimizing classes in JavaScript is the perfect example of premature optimization.

In fact, I don't even use augment in my code anymore even though its just seven lines of code. Instead, I use the following `defclass` function to create classes which don't inherit from other classes:

```javascript
function defclass(prototype) {
    var constructor = prototype.constructor;
    constructor.prototype = prototype;
    return constructor;
}

// Usage:

var Person = defclass({
    constructor: function (name) {
        this.name = name;
    },
    greet: function () {
        alert("Hello " + this.name + "!");
    }
});

// Object creation and method call:

var person = new Person("John Doe");
person.greet(); // Hello John Doe!
```

If I ever need to inherit from another class (which I usually don't) then I make use of the following `extend` function:

```javascript
function extend(constructor, keys) {
    var prototype = Object.create(constructor.prototype);
    for (var key in keys) prototype[key] = keys[key];
    return defclass(prototype);
}

// Usage:

var Man = extend(Person, {
    constructor: function (name) {
        this.name = name;
    }
});

// Object creation and method call:

var man = new Man("John Doe");
man.greet(); // Hello John Doe!
```

In practice, I have never needed to call overridden base class methods. Ever. In fact, if I had to make a chart of all the object-oriented operations I had to use then it would look like this:

1. `defclass` 99% of the time.
2. `extend` 1% of the time.
3. `super` 0% of the time.

For three lines of code, `defclass` is a very useful function. No premature optimization. No need to read the documentation of libraries like [ClassManager](https://github.com/kogarashisan/ClassManager). I can directly focus on the task at hand and optimize those things that really need optimization.

P.S. The only reason that I still maintain augment is because other people use it. Otherwise, I really don't care about it.
